editor:
  build: '.'
  restart: 'always'
  ports:
    - 80:8090
  volumes:
   - "$HOME/.ssh:/root/.ssh:ro"
  environment:
    JAVA_OPTS: '-Dfile.encoding=UTF-8 -Xms256M -Xmx1G -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC'
    SPRING_THYMELEAF_CACHE: 'true'
    FLAGS_GIT_PUSH: 'true'
    EDS_CARTAS_REPOSITORIO:
    ENDPOINTS_ENABLED: 'false'
    ENDPOINTS_JOLOKIA_ENABLED: 'false'
    ENDPOINTS_INFO_ENABLED: 'true'
    ENDPOINTS_HEALTH_ENABLED: 'true'
    ENDPOINTS_HEALTH_SENSITIVE: 'false'
    SPRING_DATA_ELASTICSEARCH_CLUSTERNODES: 'es1:9300'
  links:
    - 'postgres'
    - 'es1'
es1:
  ports:
  - 9200:9200
  container_name: 'es1'
  image: 'elasticsearch:1.7'
  command: 'elasticsearch -Des.node.name="es1"'
dbdata:
  container_name: 'dbdata'
  image: 'postgres:9.4.5'
  volumes:
    - '/dbdata'
  command: '/bin/true'
postgres:
  ports:
  - 5432:5432
  container_name: 'postgres'
  image: 'postgres:9.4.5'
  volumes_from:
    - 'dbdata'
  environment:
    PGDATA: '/dbdata'
